import React from "react";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import ClientRoot from "@/components/ClientRoot";
import Providers from "./provider/providers";
import WebSocketProvider from "@/providers/WebSocketProvider"; // ✅ ของนาน

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased overflow-y-hidden`} // ✅ ใช้ backtick ครอบ
        >
        <Providers>
            <WebSocketProvider> {/* ✅ ครอบ children ทั้งหมด */}
                <ClientRoot>
                    {children}
                </ClientRoot>
            </WebSocketProvider>
        </Providers>
        </body>
        </html>
    );
}
